version: "3"

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - viewBackend
    container_name: "view-database"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
  
  viewserver:
    build: ./server
    ports:
      - "4711:4711"
      - "4000:4000"
    networks:
      - viewBackend
    container_name: "view-server"
    links:
      - "database:db"

  documentation:
    build: ./documentation
    container_name: "documentation"
    ports:
      - "8000:8000"
    networks:
      - viewBackend

volumes:
  database:
networks:
  viewBackend:
    driver: bridge
